name: "Build with SLSA Provenance"
on:
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    permissions:
      id-token: write
      contents: read
      actions: read

    #uses: slsa-framework/slsa-github-generator/.github/workflows/builder_maven_slsa3.yml@cdeb3a916610bc00af5dee83d1acdd3c7079923a
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_maven_slsa3.yml@v1.8.0
    with:
      rekor-log-public: true
